# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170602_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='blog.Post.title', max_length=200),
        ),
    ]
